### ISSUE TITLE
AlexNet

### ISSUE THREAD

**Issue by francescocicala** [FrancescoSaverioZuppichini/glasses#24]
Add AlexNet according to the PyTorch implementation, in a more customizable and scalable way, according to the structure:
- model
-   - encoder
-   -   - gate
-   -   - blocks (scalable)
-   - decoder

**Comment by FrancescoSaverioZuppichini** [comment]
The class names do not follow python naming convention. They should be changed from 
- `AlexNet_BasicBlock` -> `AlexNetBasicBlock`
- `AlexNet_Encoder` -> `AlexNet_Encoder`

and do so on.

`ReLUInPlace` can be imported from ResNet

```
from ..resnet import ReLUInPlace
```

**Comment by francescocicala** [comment]
Change AlexNet with fix gate module

**Comment by FrancescoSaverioZuppichini** [comment]
Please remove the namespace from the blocks @francescocicala
