### ISSUE TITLE
Is there a way to change the inputlayer to a custom size?

### ISSUE THREAD

**Issue by Boraly** [FrancescoSaverioZuppichini/glasses#290]
Hello,

I would like to train a ResNet with my own dataset. This consists of HD images, so with the resolution 1280 x 720. Therefore the question, is it possible to change the input layer accordingly? And if so, how do I change it?

Thank you very much,
Boraly

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @Boraly ,

I hope you are doing great. Keep in mind that the size of the images is way too big, I advise resizing it to something less computation expensive. Saying that you can pass any resolution you want to the model, the only input constrain for the default ResNet is to have 3 channels :) 

Let me know if it works for you :) 

Cheers,

Francesco
