### ISSUE TITLE
incorrect link in the readme

### ISSUE THREAD

**Issue by Aakash-Tripathi** [FrancescoSaverioZuppichini/glasses#301]
**Describe the bug** 🐛
The "Training data-efficient image transformers & distillation through attention" link under "Stuff implemented so far:" section of the readme leads to the ViT paper and not the DeiT paper. 

**To Reproduce**
1. Go to home page 
2. Click on "Training data-efficient image transformers & distillation through attention"
3. Wrong paper opens

**Expected behavior**
The expected link is: https://arxiv.org/pdf/2012.12877.pdf

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks :) 

Fixed!
