### ISSUE TITLE
Resnet

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#4]
Implement [ResNet](https://arxiv.org/pdf/1512.03385.pdf) in a scalable way

TODO
- [x] Draw the model in Figma with every sublayer
- [x] Implement the model in a scalable way
- [x] Trace and store the model weights using `torchvision` weights
- [x] add preactivation module from [Identity Mappings in Deep Residual Networks](https://arxiv.org/pdf/1603.05027.pdf)

**Comment by francescocicala** [comment]
> We need to write a test for ResNet, I think a good lazy idea can be just passing input to the model. If we have an output it means that **at least** the weights features are correct. What do you think?

**Comment by FrancescoSaverioZuppichini** [comment]
Done!

**Comment by FrancescoSaverioZuppichini** [comment]
Add `wide` resnet from ["Wide Residual Networks"](<https://arxiv.org/pdf/1605.07146.pdf>) and resnetxt ["Aggregated Residual Transformation for Deep Neural Networks](<https://arxiv.org/pdf/1611.05431.pdf>)

**Comment by FrancescoSaverioZuppichini** [comment]
Add [Bag of Tricks for Image Classification with Convolutional Neural Networks](https://arxiv.org/pdf/1812.01187.pdf)
